plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "c:\\Users\\User\\Documents\\GitHub\\notion-autopublish"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
Content-Type = "text/html; charset=utf-8"
X-Content-Type-Options = "nosniff"
Cache-Control = "public, max-age=3600"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/*.png"

[headers.values]
Cache-Control = "public, max-age=604800, immutable"

[[headers]]
for = "/*.jpg"

[headers.values]
Cache-Control = "public, max-age=604800, immutable"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=604800"